### ISSUE TITLE
Headstock transition onto neck 

### ISSUE THREAD

**Issue by robles1999** [mnesarco/MarzWorkbench#3]
Hello Frank.  I am really thankful for your work on this FreeCAD workbench.  I really want to take full advantage of the functionality it has.  I've looked everywhere to see if I find more information on the parameters necessary on the Inkscape file so that everything imports the way it should.  At the moment I don't have any issues with the body import, but the headstock import is not working completely like on you example headstock file.  I am not sure if it's something I am doing wrong or if there is truly a bug in the code.  I am attaching the Inkscape and FreeCAD files for you to review.

I would love to talk to you if at all possible. You can contact me at:
407.733.1841
robles1999@yahoo.com

![Headstock Volute Artifact](https://user-images.githubusercontent.com/30624599/89539106-5b658680-d7c9-11ea-94cd-bf2df47fc988.png)

[Headstock Issue.zip](https://github.com/mnesarco/MarzWorkbench/files/5035176/Headstock.Issue.zip)

Thank you,
Luis Robles

**Comment by mnesarco** [comment]
Hi @robles1999 
Yes there was a bug (a tolerance problem). Fixed now.
BTW, I am rewriting everything from scratch to support better geometry, specially transitions.

The new version will have much better geometry:
![image](https://user-images.githubusercontent.com/1087317/89545372-e1cd9880-d7c8-11ea-8002-005ba0eca1b6.png)
![image](https://user-images.githubusercontent.com/1087317/89545431-f447d200-d7c8-11ea-8f39-aba2b92ad5ef.png)

**Comment by robles1999** [comment]
Great. Thank you. 

I think the ability to do the design on Inkscape and imported into FreeCAD to build the 3d was a genius idea!!

Is the correction implemented on the new re-write  or is there an update to the current one?

Also, when do you think the new version will be available?

I would like to propose some other functionalities.
1. Back and top contours 
2. Archtop

Thank you.

**Comment by robles1999** [comment]
By the way the new geometry/transition looks great.

**Comment by mnesarco** [comment]
@robles1999 

-  The fix is in the current one.
-  I already started the archtop work in the new version.
- Back and Top contours are very easy to implement. Great idea.
- The new version will be public in about one month I hope. It is a complete rewrite, and contains double asymmetric neck profiles, BuiltIn neck profile editor, Custom volute geometry (imported from svg), Custom Heel geometry (svg), way better transition geometry, nut part witth equal center and equal gap support, ... And 1000x performance boost.

![image](https://user-images.githubusercontent.com/1087317/89553397-121a3480-d7d3-11ea-814d-2f3f8d632d26.png)

![image](https://user-images.githubusercontent.com/1087317/89553470-2c541280-d7d3-11ea-9f7c-fe6c11f4b74f.png)

![image](https://user-images.githubusercontent.com/1087317/89553516-3d048880-d7d3-11ea-9160-3dbdf7aa5134.png)

**Comment by robles1999** [comment]
Wow!!! that's going to be amazing.  

I downloaded the 0.21 version just now to give it a try, and I am still getting the same result on the volute when I add the headstock.

![Headstock Volute Artifact2](https://user-images.githubusercontent.com/30624599/89557276-8dceae00-d7e0-11ea-915e-83f48b153305.png)

**Comment by mnesarco** [comment]
Hi, mm it is fixed in github but not in 0.21. Give some minutes to upload 0.22

**Comment by mnesarco** [comment]
It is fixed in release 0.0.23 now.

**Comment by robles1999** [comment]
Ok. Thank you.

By the way I know you are developing and testing in Linux, I have Windows and Mac machines, so I'd be more than happy to help you test the workbench on the 2 systems.

**Comment by mnesarco** [comment]
> Ok. Thank you.
> 
> By the way I know you are developing and testing in Linux, I have Windows and Mac machines, so I'd be more than happy to help you test the workbench on the 2 systems.

Thank you, it sounds great. Testing in windows is a pain for me because I use a very slow Windows virtual machine. And testing in Mac is just impossible to me because I don't have one :D

**Comment by robles1999** [comment]
For sure. Is the least I can do.  

I am getting to test the .23 release now.

**Comment by robles1999** [comment]
The issue is gone.  There's a small issued with the Profile "D".  I don't know if it is that I have to change the parameter when changing the Profiles or is a small code fix.  I don't 100% understand all the parameters yet and I am still playing with them to see the effects of each.  However, here are some pictures of the different profiles and their settings.

![Headstock Volute D v23_1](https://user-images.githubusercontent.com/30624599/89567748-29b3e600-d7f0-11ea-86c3-4f4b44573e2c.png)
![Headstock Volute D2 v23](https://user-images.githubusercontent.com/30624599/89567750-2a4c7c80-d7f0-11ea-83e5-61dda2b2ca58.png)
![Headstock Volute V v23](https://user-images.githubusercontent.com/30624599/89567751-2a4c7c80-d7f0-11ea-88f9-9e0a6668a373.png)
![Headstock Volute Classic v23](https://user-images.githubusercontent.com/30624599/89567752-2a4c7c80-d7f0-11ea-9cc9-012d0d9ba86a.png)

**Comment by robles1999** [comment]
The addition of the Constructions lines is great. Another helpful functions would be to be able to Chamfer and Fillet.  I was able to do it by copying the body over to the Parts Design workbench to Fillet and do some boolean functions, but it would be nice to have it in your workbench or have it be a Body rather than a Part.

**Comment by mnesarco** [comment]
All the code for transitions (heel and headstock) was rewritten in the new version, I will not port that to this version. :(
Also the neck profile algorithm is completely different in new version and will be not ported back.
Filled and Chamfer are standard FreeCAD features, the idea is to use them with the generated solids.

**Comment by robles1999** [comment]
I agree. No need to port it back. 

Thank you for the fix of the volute. This last version alone is of immense help to us non 3D Designer luthiers. It surely has been a struggle to dive into the new technology but I  know it'll be worth it. Again thank you for your work. I look forward to the new version. If you need any help testing the new version please feel free to reach out to me.

**Comment by robles1999** [comment]
That looks fantastic!!. Patiently waiting for the complete version.

**Comment by mnesarco** [comment]
Advanced custom headstock shape with custom volute, plus double asymmetric neck profile, plus break angle:

![image](https://user-images.githubusercontent.com/1087317/91770791-6d0f3380-eba7-11ea-9068-af3ecf5c4029.png)

Everything from a simple SVG contour.

Comming soon...

**Comment by robles1999** [comment]
Mi hrno. eso esta de maravilla. Is this going to be a stand alone app or a FreeCad workbench?

**Comment by robles1999** [comment]
Just food for thought. If it is a stand alone app, an integrated simple g-code generator like Mash Cam would be the icing on the cake.

**Comment by mnesarco** [comment]
It is a standalone app now, but with FreeCAD integration. Everything was rewritten in C++. FreeCAD is an excellent CAD software but as all 3D Cad tools it is very complex for the average Luthier. The main goal of this project is to provide something simple to use with domain specific terminology but powerful enough to model parametric guitar designs without beign a CAD expert.

**Comment by robles1999** [comment]
Thats great. You are truly a blessing. I've been having a hard time working with FreeCad. I was using Fusion 360 and got decent at it but don't like the fact that they can stop providing it for free at anytime. In the last 2 months I've been using designspark mechanical and by far is the most user friendly Cad software I've used. It is very powerful and I've been able to create pretty much anything I can think of really fast without any problems. However having your parametric workbench for building guitars is going to make everything so simple and really expand the possibilities.

**Comment by robles1999** [comment]
Here are some samples of what I've been able to build on DesignSpark.  These are just shapes I built while learning to use the software, no real guitar dimensions.

![Sample 1](https://user-images.githubusercontent.com/30624599/91784038-d5720b00-ebcf-11ea-9aa2-276108c2d66b.png)
![Sample 2](https://user-images.githubusercontent.com/30624599/91784042-d60aa180-ebcf-11ea-811b-10bc75d36de2.png)
![Sample 3](https://user-images.githubusercontent.com/30624599/91784043-d6a33800-ebcf-11ea-80c3-2948159ca820.png)
![Sample 4](https://user-images.githubusercontent.com/30624599/91784044-d6a33800-ebcf-11ea-95ad-ca15ffa99893.png)
![Sample 5](https://user-images.githubusercontent.com/30624599/91784045-d6a33800-ebcf-11ea-8fb1-e225da56f6b6.png)
![Sample 6](https://user-images.githubusercontent.com/30624599/91784046-d73bce80-ebcf-11ea-8345-3c192c3859e1.png)

**Comment by mnesarco** [comment]
I have achieved near perfect surfaces:

![image](https://user-images.githubusercontent.com/1087317/93716909-f6c37880-fb37-11ea-88fd-995dbabfc295.png)

Neck and Fretboard generated in 1.5 seconds.
- Asymmetric neck profiles (double asymmetric)
- Custom asymmetric heel
- Custom headstock
- Custom asymmetric volute
- Custom truss-rod alignment
- Custom headstock angle, neck angle,, zero-fret, scales, radiuses, etc...

**Comment by robles1999** [comment]
You are killing me. 8-)  That is crazy good!!!!

**Comment by mnesarco** [comment]
> You are killing me. 8-) That is crazy good!!!! 1.5 seconds is amazing. That's some serious code for all the calculations it has to compute. Great job!!

Calculations are the fast part. OCCT boolean operations are the slowest, so I have managed to avoid them as much as possible and I use a highly parallelized code.

**Comment by PuzzlingMatt** [comment]
Wow, just wanted to that from reading this thread it looks like this are looking really really good. Look to be able to have a go with the new version soon though I'm having a decent amount of success with the current version. Suspect you might have some more users headed your since it looks like people have started to drop F360 with the recent licence changes.

**Comment by mnesarco** [comment]
@PuzzlingMatt yes I knew about the F360 exodus, FreeCAD community is like a refugee land these days. I am working hard to release something as soon as possible. But this is not an easy task. Specially now that I rewrote everything from scratch in C++. But the results are worth the pain.

**Comment by PuzzlingMatt** [comment]
@mnesarco anything I can do to help? I can c++ but dont have a lot of experience with freecad - some of its quirks are taking a bit of getting used to! I've actually had some good results with the current version of the workbench (it works fine on windows btw) - just experimenting with the freecad cam stuff now.

**Comment by mnesarco** [comment]
Hi @PuzzlingMatt I am having some progress, but there are not deadlines. I do this for fun and love in my spare time. The current dev version is a very different beast compared to the python workbench. This is the parametric double asymmetric neck profile editor:

![image](https://user-images.githubusercontent.com/1087317/96538125-68890200-125d-11eb-9356-13af7e1486e1.png)

By the moment the trussrod channel is aligned with the spine of the profile because I initially thougt that it was the most logic placement. But some more experienced Luthiers think that the trussrod must be aligned with centerline unconditionally, others prefer to decide case by case. So I am adding different alignment options here.

I am also working on more parallelization optimizations, better surfaces, and a very convenient appication file format. I started this as a very simple freecad addon, but it is becoming something more serious now.

**Comment by robles1999** [comment]
Loving it.

**Comment by PuzzlingMatt** [comment]
Agreed, looks very nice. I guess it'll be something that we might see for sale at some point? Would save me a bucket load of time if I didnt have to model body contours and things by hand since thats always a bit of a faff! Happy to help out with testing or maintaining a windows build if needed in the future.

**Comment by dantahoua** [comment]
A bit out of line, but as soon as I manage to compile Freecad 0.19 on my Calculate Linux, count me in the testing guys for your Guitar Design Workbench! It's awesome!!! What Linux distrib. do you use?

**Comment by mnesarco** [comment]
Thank you @dantahoua , The version I am working on now does not depend on Freecad, I plan to release it as a standalone AppImage. I am using Mint 19.3 right now.

**Comment by dantahoua** [comment]
That sound interesting!!! :)

**Comment by robles1999** [comment]
Hello Frank and happy new year!

I was wondering how the project is going. I finally got a CNC and was hoping to design and acoustic guitar. I wanted to check with you before I started designing everything myself which it will take a lot longer than with your software.

**Comment by mnesarco** [comment]
Hi @robles1999 , 
The project was paused for some months but I am actively working on it again. I hope I will release an update soon, but I cannot guarantee any specific release date.

**Comment by robles1999** [comment]
Hi Frank. Thanks for the update, I was just wondering because I hadn't heard anything from you in a while.

**Comment by brotherdust** [comment]
> It is a standalone app now, but with FreeCAD integration. Everything was rewritten in C++. FreeCAD is an excellent CAD software but as all 3D Cad tools it is very complex for the average Luthier. The main goal of this project is to provide something simple to use with domain specific terminology but powerful enough to model parametric guitar designs without beign a CAD expert.

@mnesarco , you mentioned that it's now written in C++, but didn't mention a link! Please advise where one can get the rewrite! Thank you!

**Comment by mnesarco** [comment]
@brotherdust , It is not public yet.

**Comment by evfool** [comment]
@mnesarco if you need help developing and would like to make the current state public, I would be interested in also coding, and also using it. Amazing what you have achieved with this project so far.

**Comment by mnesarco** [comment]
Hi @evfool thank you for the offer. I am closer to release a new version, here are some pictures:

![screenshot_9](https://user-images.githubusercontent.com/1087317/123797057-6c205e80-d8ab-11eb-92c6-486ae6554a22.png)

![screenshot_5](https://user-images.githubusercontent.com/1087317/123797097-717da900-d8ab-11eb-909c-9cc243b4e95a.png)

![image](https://user-images.githubusercontent.com/1087317/123798012-66774880-d8ac-11eb-9342-c51f79389475.png)

**Comment by brotherdust** [comment]
> Hi @evfool thank you for the offer. I am closer to release a new version, here are some pictures:
> 
> 
> 
> ![screenshot_9](https://user-images.githubusercontent.com/1087317/123797057-6c205e80-d8ab-11eb-92c6-486ae6554a22.png)
> 
> 
> 
> ![screenshot_5](https://user-images.githubusercontent.com/1087317/123797097-717da900-d8ab-11eb-909c-9cc243b4e95a.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1087317/123798012-66774880-d8ac-11eb-9342-c51f79389475.png)
> 
> 

Very very cool! I'm so excited for a release. Do you need help with docs? I'm good at that.

**Comment by brotherdust** [comment]
@mnesarco , just wanted to check back in with you on your C++ re-write. Was using Guitar Workbench today and ran into some limitations and it seems like your rewrite would fix them. Do you need a tester? I'd like to help somehow, if possible.
Thanks!

**Comment by mnesarco** [comment]
Hi @brotherdust I am close but not ready yet to release something:


https://user-images.githubusercontent.com/1087317/133135615-c64072d2-be6f-4b2f-b190-4a421d516af3.mp4

**Comment by brotherdust** [comment]
@mnesarco Will it support headless, multiscale builds? 😁

**Comment by mnesarco** [comment]
Yes it already support headless and multiscale.

**Comment by brotherdust** [comment]
> Yes it already support headless and multiscale.

Oh man! That's incredibly exciting! I'm just a hobbyist but I would seriously pay at least $100 for this software. You got a place I can donate? 😉

**Comment by mnesarco** [comment]
I am not receiving donations yet because there is no public product yet. Thank you for your offer. Stay tuned, I want to release the first version this year.

**Comment by mnesarco** [comment]
Hello @brotherdust ,
The project was seeping for a long time this year, but I have news, I have Gordons Surfaces now thanks to Tigl project.

![image](https://user-images.githubusercontent.com/1087317/207055882-7a8c2e4f-e9a6-4044-8978-96e976f06d27.png)

It means that finally I can provide transitions for heel-barrel and barrel-headstock with proper continuity. That was the missing piece for an initial release.

**Comment by brotherdust** [comment]
> Hello @brotherdust ,
> 
> The project was seeping for a long time this year, but I have news, I have Gordons Surfaces now thanks to Tigl project.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1087317/207055882-7a8c2e4f-e9a6-4044-8978-96e976f06d27.png)
> 
> 
> 
> It means that finally I can provide transitions for heel-barrel and barrel-headstock with proper continuity. That was the missing piece for an initial release.
> 
> 

So excited! When?!

**Comment by mnesarco** [comment]
I can't compromise a date. Sorry.
